---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_url: https://gist.githubusercontent.com/loren/80d42f115fedbdd7635489ecbcfeb121/raw/6d22d4deda5f8d4e4d22ab57b2538fc7a5beaf14/install.sh

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      customize:
        memory: 512
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[googl_api_cookbook::setup]
      - recipe[googl_api_cookbook::deploy]
    attributes:
    data_bags_path: "test/integration/data_bags"

