---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  chef_omnibus_url: https://gist.githubusercontent.com/loren/80d42f115fedbdd7635489ecbcfeb121/raw/6d22d4deda5f8d4e4d22ab57b2538fc7a5beaf14/install.sh

platforms:
  - name: ubuntu-16.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[googl_api_cookbook::setup]
      - recipe[googl_api_cookbook::deploy]
    attributes:
    data_bags_path: "test/integration/data_bags"
