name 'googl_api_cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures googl_api_cookbook'
long_description 'Installs/Configures googl_api_cookbook'
issues_url 'https://github.com/GovWizely/googl_api_cookbook/issues'
source_url 'https://github.com/GovWizely/googl_api_cookbook'
version '0.1.0'

depends 'apt'
depends 'nginx', '~> 2.7.6'
depends 'application_ruby', '~> 4.0.1'
depends 'application_git'
depends 'poise-ruby-build'
depends 'magic_shell'
